# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tutorial3' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tutorial3
  pod 'SnapKit'
  pod 'Moya'
  pod 'Kingfisher'

end
